Search for wildcard

diff --git a/packages/idp/packaging b/packages/idp/packaging
--- a/packages/idp/packaging
+++ b/packages/idp/packaging
@@ -12,12 +12,10 @@ else
   exit 1
 fi
 
-if [[ -f $archive ]] ; then
-  echo "Archive found"
-else
-  echo "Archive not found"
-  exit 1
-fi
+for f in java8/openjdk-*.tar.gz; do
+  [ -e "$f" ] && echo "Archive found" || echo "Archive not found"; exit 1
+  break
+done
 
 echo "Extracting java archive..."
 mkdir jre
